---
title: "AGBRESA Preprocess Biomarker"
author: "A Stahn"
date: "10/25/2021"
output: html_document
---
# Prepare Script
## Required Packages
```{r load required packages, message = FALSE}
library(readxl)#read xls
library(openxlsx) #save tables
library(plyr) #means across subjects and groups, change scores
library(dplyr) #distinct function
library(tidyverse)
library(naniar)
```
## Print Session Info
```{r print R and package versions}
print(sessionInfo())
```
## Functions
```{r function for preprocessing}
# Preprocessing function blood
func_clean_var <- function(x){
  x$time.f <- x$file
  x$time.f <- gsub("AGBR-", "", x$time.f)
  x$time.f <- gsub( "-AS.*$", "", x$time.f ) #extract everythign after -AS from start
  x$time.f <- gsub('(.*)-\\w+', '\\1', x$time.f) #delete everyhting after last underscore
  x$id <- x$file
  x$id <- gsub("AGBR-", "", x$id)
  x$id <- gsub( "-AS.*$", "", x$id )
  x$id <- gsub(".*-","",x$id)
  x$tod <- x$file
  x$tod <- gsub("AGBR-", "", x$tod)
  x$tod <- gsub(".{3}$", "", x$tod)
  x$tod  <- gsub( "^*.-", "", x$tod  ) #delete everything before _
  x$tod  <- gsub(".*-","",x$tod)
  x$tod  <- gsub("AS","1",x$tod)
  x <- x[-c(1)]
  return(x)
}

# Preprocessing function cortisol
func_clean_var_cort <- function(x){
  x$time.f <- x$file
  x$time.f <- gsub("AGBR-", "", x$time.f)
  x$time.f <- gsub( "-AS.*$", "", x$time.f ) #extract everythign after -AS from start
  x$time.f <- gsub('(.*)-\\w+', '\\1', x$time.f) #delete everyhting after last underscore
  x$id <- x$file
  x$id <- gsub("AGBR-", "", x$id)
  x$id <- gsub( "-AS.*$", "", x$id )
  x$id <- gsub(".*-","",x$id)
  x$tod <- x$file
  x$tod <- gsub("AGBR-", "", x$tod)
  x$tod <- gsub("-Sal", "", x$tod)
  x$tod  <- gsub( "^*.-", "", x$tod  ) #delete everything before _
  x$tod  <- gsub(".*-","",x$tod)
  x$tod  <- gsub("AS","1",x$tod)
  x <- x[-c(1)]
  return(x)
}

# Helper function for bdc mean and sd, forward to 'func_z'
func_bdc <- function(x) (x %>%
  filter(!!!bdc) %>% # requires input as cat
  group_by(variable) %>%
  dplyr::summarize(
    mean_bdc = mean(value, na.rm=T),
    sd_bdc = sd(value, na.rm=T)
    )
  )

# Function for z scores, requires 'func_bdc'
func_z <- function(x) {
  tmp <- reshape2::melt(x, id.vars = id_vars) 
  dat_bdc <- func_bdc(tmp)
  tmp <- merge(tmp, dat_bdc, by ="variable")
  tmp$z <- (tmp$value - tmp$mean_bdc) / tmp$sd_bdc
  tmp$variable <- paste(tmp$variable, "z", sep="_")
  tmp_id_var <- paste(id_vars, collapse = "+")
  id_vars_dep <- paste(tmp_id_var, "~ variable" )
  tmp <- reshape2::dcast(tmp, id_vars_dep, value.var = "z")
  return(tmp)
}
```

# Load and Preprocess Data
```{r biomarker}
# Read data
# Data bdnf
df_bdnf <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/BDNF data.xlsx", sheet = 1)
df_bdnf <- df_bdnf[c(2:5)]
df_bdnf <- df_bdnf[-c(1:2,78:81,154:157,232:235),]
names(df_bdnf)[names(df_bdnf)=="...2"] <- "file"
names(df_bdnf)[names(df_bdnf)=="BDNF"] <- "bdnf"
names(df_bdnf)[names(df_bdnf)=="...4"] <- "cv_bdnf"
names(df_bdnf)[names(df_bdnf)=="...5"] <- "comment_bdnf"

# Preprocess and clean data
df_tmp <- df_bdnf
df_bdnf <- func_clean_var(df_tmp)

# Data igf
df_igf <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/Stahn IGF-1 Raw Data 052721.xlsx", sheet = 1)
df_igf <- df_igf[c(2,9)]
df_igf <- df_igf[-c(1:2),]
names(df_igf)[names(df_igf)=="...2"] <- "file"
names(df_igf)[names(df_igf)=="...9"] <- "igf"

# Preprocess and clean data
df_tmp <- df_igf
df_igf <- func_clean_var(df_igf)

# Data vegf
df_vegf <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/VEGF-A data.xlsx", sheet = 1)
df_vegf <- df_vegf[c(2:5)]
df_vegf <- df_vegf[-c(1:2,78:81,154:157,232:235),]
names(df_vegf)[names(df_vegf)=="...2"] <- "file"
names(df_vegf)[names(df_vegf)=="VEGF-A"] <- "vegf"
names(df_vegf)[names(df_vegf)=="...4"] <- "cv_vegf"
names(df_vegf)[names(df_vegf)=="...5"] <- "comment_vegf"

# Preprocess and clean data
df_tmp <- df_vegf
df_vegf <- func_clean_var(df_vegf)

# Data il1b
df_il1b <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/il1b Data Report.xlsx", sheet = 1)
df_il1b <- df_il1b[c(2:5)]
df_il1b <- df_il1b[-c(1:2,78:81,154:157,232:235),]
names(df_il1b)[names(df_il1b)=="...2"] <- "file"
names(df_il1b)[names(df_il1b)=="IL1b"] <- "il1b"
names(df_il1b)[names(df_il1b)=="...4"] <- "cv_il1b"
names(df_il1b)[names(df_il1b)=="...5"] <- "comment_il1b"
df_il1b$il1b <- gsub("[*]","",df_il1b$il1b) #remove asterisk

# Preprocess and clean data
df_tmp <- df_il1b
df_il1b <- func_clean_var(df_il1b)


# Data il6
df_il6 <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/IL6 Data Report.xlsx", sheet = 1)
df_il6 <- df_il6[c(2:5)]
df_il6 <- df_il6[-c(1:2,78:81,154:157,232:235),]
names(df_il6)[names(df_il6)=="...2"] <- "file"
names(df_il6)[names(df_il6)=="IL-6"] <- "il6"
names(df_il6)[names(df_il6)=="...4"] <- "cv_il6"
names(df_il6)[names(df_il6)=="...5"] <- "comment_il16"
df_il6$il6 <- gsub("[*]","",df_il6$il6) #remove asterisk

# Preprocess and clean data
df_tmp <- df_il6
df_il6 <- func_clean_var(df_il6)

# Data tnfa
df_tnfa <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/TNF Report.xlsx", sheet = 1)
df_tnfa <- df_tnfa[c(2:5)]
df_tnfa <- df_tnfa[-c(1:2,78:81,154:157,232:235),]
names(df_tnfa)[names(df_tnfa)=="...2"] <- "file"
names(df_tnfa)[names(df_tnfa)=="TNF-a"] <- "tnfa"
names(df_tnfa)[names(df_tnfa)=="...4"] <- "cv_tnfa"
names(df_tnfa)[names(df_tnfa)=="...5"] <- "comment_tnfa"
df_tnfa$tnfa <- gsub("[*]","",df_tnfa$tnfa) #remove asterisk

# Preprocess and clean data
df_tmp <- df_tnfa
df_tnfa <- func_clean_var(df_tnfa)

# Data nfl
df_nfl <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/NFL Report.xlsx", sheet = 1)
df_nfl <- df_nfl[c(2:5)]
df_nfl <- df_nfl[-c(1:2,78:81,154:157,232:235),]
names(df_nfl)[names(df_nfl)=="...2"] <- "file"
names(df_nfl)[names(df_nfl)=="Human NF-L"] <- "nfl"
names(df_nfl)[names(df_nfl)=="...4"] <- "cv_nfl"
names(df_nfl)[names(df_nfl)=="...5"] <- "comment_nfl"
df_nfl$nfl <- gsub("[*]","",df_nfl$nfl) #remove asterisk

# preprocess and clean data
df_tmp <- df_nfl
df_nfl <- func_clean_var(df_nfl)

# Data cortisol
df_cort <- read_excel("/Users/astahn/Publications/AGBRESA/Data/Biomarker/TCL/Stahn Cortisol Raw Data 052721_cor.xlsx", sheet = 1)
df_cort <- df_cort[c(2,9)]
df_cort <- df_cort[-c(1:2),]
names(df_cort)[names(df_cort)=="...2"] <- "file"
names(df_cort)[names(df_cort)=="...9"] <- "cort"

#df_cort <- df_cort[-c(299),] #delete double entry
# preprocess and clean data
df_tmp <- df_cort
df_cort <- func_clean_var_cort(df_cort)

# Rearrange columns
df_cort <- df_cort[c(3,2,4,1)]


df_cort <- as_tibble(df_cort)

# Convert var types
df_cort[c(1:3)] <- lapply(df_cort[c(1:3)], as.factor)
df_cort[c(4)] <- lapply(df_cort[c(4)], as.numeric)

```
# Combine
```{r combine dfs}
df_bio_tmp <- merge(df_bdnf, df_igf, by=c("id","time.f","tod"))
df_bio_tmp <- merge(df_bio_tmp, df_vegf, by=c("id","time.f","tod"))
df_bio_tmp <- merge(df_bio_tmp, df_nfl, by=c("id","time.f","tod"))
df_bio_tmp <- merge(df_bio_tmp, df_il1b, by=c("id","time.f","tod"))
df_bio_tmp <- merge(df_bio_tmp, df_il6, by=c("id","time.f","tod"))
df_blood <- merge(df_bio_tmp, df_tnfa, by=c("id","time.f","tod"))
df_blood <- as_tibble(df_blood)
```
# Relabel time.f
```{r relabel}
# Blood
df_blood$time.f <- factor(df_blood$time.f , levels=c("BDC-6", "BDC-3", "HDT2", "HDT14", "HDT30", "HDT42", "HDT56", "R+1", "R+10"), ordered = TRUE)  

df_blood$time.n <- plyr::revalue(df_blood$time.f, c("BDC-6" = "1", "BDC-3" = "2", "HDT2" = "3", "HDT14" = "4", "HDT30" = "5", "HDT42" = "6", "HDT56" = "7", "R+1" = "8", "R+10" = "9"))
df_blood <- df_blood[c(1:2, 23, 3, 4, 7:8, 11, 14, 17, 20)]
df_blood[c(1,2,4)] <- lapply(df_blood[c(1,2,4)], as.factor)
df_blood[c(3, 5:11)] <- lapply(df_blood[c(3, 5:11)], as.numeric)

# Cortisol
df_cort$time.f <- factor(df_cort$time.f , levels=c("BDC-6", "BDC-3", "HDT2", "HDT14", "HDT30", "HDT42", "HDT56", "R+1", "R+10"), ordered = TRUE)  

df_cort$time.n <- plyr::revalue(df_cort$time.f, c("BDC-6" = "1", "BDC-3" = "2", "HDT2" = "3", "HDT14" = "4", "HDT30" = "5", "HDT42" = "6", "HDT56" = "7", "R+1" = "8", "R+10" = "9"))
df_cort <- df_cort[c(1:3,5,4)]
df_cort$time.n <- as.character((df_cort$time.n))
df_cort$time.n <- as.numeric((df_cort$time.n))
```
# Remove outliers
```{r remove outliers}
# Blood
# Morning
df_blood_morn <- subset(df_blood, tod == "1")

dvList <- names(df_blood_morn[c(5:11)])
outliers <- lapply(df_blood_morn[dvList], boxplot.stats) #show outliers

df_blood_del_outlier <- df_blood_morn %>% 
  replace_with_na(replace = list(bdnf = outliers$bdnf$out)) %>% 
  replace_with_na(replace = list(igf = outliers$igf$out)) %>% 
  replace_with_na(replace = list(vegf = outliers$vegf$out)) %>% 
  replace_with_na(replace = list(il1b = outliers$il1b$out)) %>% 
  replace_with_na(replace = list(il6 = outliers$il6$out)) %>% 
  replace_with_na(replace = list(tnfa = outliers$tnfa$out)) %>% 
  replace_with_na(replace = list(igf = outliers$igf$out)) %>% 
  replace_with_na(replace = list(nfl = outliers$nfl$out))

df_blood_morn <- df_blood_del_outlier

# Post AG
df_blood_postAG <- subset(df_blood, tod == "2")

dvList <- names(df_blood_postAG[c(5:11)])
outliers <- lapply(df_blood_postAG[dvList], boxplot.stats) #show outliers

df_blood_del_outlier <- df_blood_postAG %>% 
  replace_with_na(replace = list(bdnf = outliers$bdnf$out)) %>% 
  replace_with_na(replace = list(igf = outliers$igf$out)) %>% 
  replace_with_na(replace = list(vegf = outliers$vegf$out)) %>% 
  replace_with_na(replace = list(il1b = outliers$il1b$out)) %>% 
  replace_with_na(replace = list(il6 = outliers$il6$out)) %>% 
  replace_with_na(replace = list(tnfa = outliers$tnfa$out)) %>% 
  replace_with_na(replace = list(igf = outliers$igf$out)) %>% 
  replace_with_na(replace = list(nfl = outliers$nfl$out))

df_blood_postAG <- df_blood_del_outlier

# Cortisol

# Morning
df_cort_morn <- subset(df_cort, tod == "1")
dvList <- names(df_cort[c(5)])
outliers <- lapply(df_cort_morn[dvList], boxplot.stats) #show outliers

df_cort_del_outlier <- df_cort_morn %>% 
  replace_with_na(replace = list(cort = outliers$cort$out)) 

df_cort_morn <- df_cort_del_outlier

# Evening
df_cort_eve <- subset(df_cort, tod == "2")
dvList <- names(df_cort[c(5)])
outliers <- lapply(df_cort_morn[dvList], boxplot.stats) #show outliers

df_cort_del_outlier <- df_cort_eve %>% 
  replace_with_na(replace = list(cort = outliers$cort$out))

df_cort_eve <- df_cort_del_outlier

#df_cort_del_outlier <- reshape2::melt( df_cort_del_outlier, id.vars = c("id", "time.f", "time.n") )
```
# Add z scores
```{r z scores}
# Morning
# Define id vars for long format, and bdc data
id_vars <- c('id', 'time.f', 'time.n', 'tod')
bdc <- quote( time.f == "BDC-6" | time.f == "BDC-3" )

# Run z scores
df_blood_z_morn <- func_z(df_blood_morn)
df_blood_z_morn <- as_tibble(df_blood_z_morn)
df_blood_z_morn <- droplevels(df_blood_z_morn)

# Post AG
# Add bdc to post AG data
tmp <- df_blood_morn %>% filter(!!!bdc)
df_blood_z_postAG <- rbind(tmp, df_blood_postAG)

# Define id vars for long format, and bdc data
id_vars <- c('id', 'time.f', 'time.n', 'tod')
bdc <- quote( time.f == "BDC-6" | time.f == "BDC-3" )

# Run z scores
df_blood_z_postAG <- func_z(df_blood_z_postAG)
df_blood_z_postAG <- as_tibble(df_blood_z_postAG)

# Drop BDC
df_blood_z_postAG <- subset(df_blood_z_postAG, time.f != "BDC-6" & time.f != "BDC-3")
df_blood_z_postAG <- droplevels(df_blood_z_postAG)

# Cortisol
# Morning
df_cort_z_morn <- subset(df_cort, tod == "1")
df_cort_z_eve <- subset(df_cort, tod == "2")

# define id vars for long format, and bdc data
id_vars <- c('id', 'time.f', 'time.n', 'tod')
bdc <- quote( time.f == "BDC-6" | time.f == "BDC-3" )

# Run z scores
df_cort_z_morn <- func_z(df_cort_z_morn)
df_cort_z_morn <- as_tibble(df_cort_z_morn)
df_cort_z_morn <- droplevels(df_cort_z_morn)

df_cort_z_eve <- func_z(df_cort_z_eve)
df_cort_z_eve <- as_tibble(df_cort_z_eve)
df_cort_z_eve <- droplevels(df_cort_z_eve)
```

# Save data
```{r export data}
list_of_datasets <- list("Data Cortisol" = df_cort,
                         "Data Cortisol Morning z" = df_cort_z_morn,
                         "Data Cortisol Evening z" = df_cort_z_eve,
                         "Data Blood" = df_blood,
                         "Data Blood Morning z" = df_blood_z_morn,
                         "Data Blood Post AG z" = df_blood_z_postAG)
write.xlsx(list_of_datasets, file = "./Data/Data Biomarker.xlsx", overwrite = TRUE)
```
